NumPy is the standard numerical library available in the `python` environment. It allows quicker computations on array-like structures. Central objects in the `numpy` library are `ndarray`s. These are *homogenuous* $n$-dimensional arrays ; elements of the array are all of the same type. 

Efficiency of `ndarray` objects come from the fact that element-wise operations are `C` implemented to ensure low complexity. One can translate loop-like operations on array-like structures into available corresponding implementation for `ndarrays`. This process is called *vectorisation* ; it improves efficiency and must be on mind when dealing with scientific programming. 

## Defining an `ndarray` object

In [2]:
import numpy as np

In [3]:
np_matrix = np.array([[1, 2, 3, 4], [-1, 0, 1, 2]], dtype='float64')
np_matrix

array([[ 1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.]])

In [4]:
np_matrix.dtype

dtype('float64')

One can build up a $2$-dimensional `ndarray` object as a list of lists. The matrix in such a case is given line by line. An `ndarray` object comes with a lot of attributes, we'll be seeing a number of them while going on. Here are the ones enclosing the shape of the array.

In [5]:
np_matrix.ndim

2

In [6]:
np_matrix.shape

(2, 4)

In many cases one to initialize an `ndarray`, either by giving random coefficients to the elements of the matrix or by giving a specified type matrix. Here are the standard available `ndarray`s.

In [7]:
Z = np.zeros(4, dtype='float64')

In [8]:
Z.shape
Z

array([ 0.,  0.,  0.,  0.])

In [9]:
np.zeros((3, 4), dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [11]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [12]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [13]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

To build up a random `ndarray` one can use available `numpy` built-in random generators.

In [14]:
np.random.rand(2, 4)

array([[ 0.36170135,  0.44862962,  0.34524141,  0.05102319],
       [ 0.26341254,  0.14143642,  0.0870751 ,  0.14509846]])

In [15]:
np.random.randn(2, 4)

array([[-0.22226902, -0.83376871,  1.81369636, -0.45445026],
       [ 0.00246119, -0.44749118,  0.58093413, -1.73171106]])

In [16]:
np.random.randint?

A useful way of building up matrices out of lists is to reshape the standard one-line corresponding numpy array object. 

In [17]:
np_A = np.random.randint(10, size=20)
np_A

array([3, 3, 2, 1, 6, 3, 9, 1, 8, 6, 4, 4, 0, 5, 9, 6, 0, 0, 1, 6])

In [18]:
np_A.ndim

1

In [19]:
np_A = np_A.reshape(4, -1)  # -1 here leaves the choice to python.
np_A

array([[3, 3, 2, 1, 6],
       [3, 9, 1, 8, 6],
       [4, 4, 0, 5, 9],
       [6, 0, 0, 1, 6]])

In [20]:
np_A.shape

(4, 5)

In [21]:
np_A.T

array([[3, 3, 4, 6],
       [3, 9, 4, 0],
       [2, 1, 0, 0],
       [1, 8, 5, 1],
       [6, 6, 9, 6]])

Another useful array definition is the one given by `arange`. It is the `numpy` version of `python` range. It returns a one dimensional array containing an arithmetic sequence of integers following range syntax.

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In many applications one looks for a sequence of floats modelling the real line. A way of generating such a `numpy` array is to use the `linspace` function.

In [26]:
np.linspace?

In [27]:
np.linspace(1, 10, 100)

array([  1.        ,   1.09090909,   1.18181818,   1.27272727,
         1.36363636,   1.45454545,   1.54545455,   1.63636364,
         1.72727273,   1.81818182,   1.90909091,   2.        ,
         2.09090909,   2.18181818,   2.27272727,   2.36363636,
         2.45454545,   2.54545455,   2.63636364,   2.72727273,
         2.81818182,   2.90909091,   3.        ,   3.09090909,
         3.18181818,   3.27272727,   3.36363636,   3.45454545,
         3.54545455,   3.63636364,   3.72727273,   3.81818182,
         3.90909091,   4.        ,   4.09090909,   4.18181818,
         4.27272727,   4.36363636,   4.45454545,   4.54545455,
         4.63636364,   4.72727273,   4.81818182,   4.90909091,
         5.        ,   5.09090909,   5.18181818,   5.27272727,
         5.36363636,   5.45454545,   5.54545455,   5.63636364,
         5.72727273,   5.81818182,   5.90909091,   6.        ,
         6.09090909,   6.18181818,   6.27272727,   6.36363636,
         6.45454545,   6.54545455,   6.63636364,   6.72

## Slicing 

There are many different ways of slicing an `ndarray`. One needs to be careful about the fact that some give back a view on a slice of the array others copy part of it.

In [49]:
np_A

array([[0, 0, 1, 0, 0],
       [9, 8, 6, 6, 2],
       [4, 5, 4, 1, 0],
       [2, 5, 2, 3, 9]])

Standard slicing gives views on subelements of `ndarray`. 

In [50]:
np_A[1]

array([9, 8, 6, 6, 2])

In [51]:
np_A[1, 0]

9

In [52]:
np_A[:, 0]

array([0, 9, 4, 2])

In [53]:
np_A[1:3]

array([[9, 8, 6, 6, 2],
       [4, 5, 4, 1, 0]])

In [54]:
np_A[1:3, 1:4]

array([[8, 6, 6],
       [5, 4, 1]])

Boolean choices.

In [55]:
np_A

array([[0, 0, 1, 0, 0],
       [9, 8, 6, 6, 2],
       [4, 5, 4, 1, 0],
       [2, 5, 2, 3, 9]])

In [56]:
np_A[[False, True, False, True]] 

array([[9, 8, 6, 6, 2],
       [2, 5, 2, 3, 9]])

In [57]:
np_A[0] < 2

array([ True,  True,  True,  True,  True], dtype=bool)

In [58]:
np_A[:, np_A[0] < 2]

array([[0, 0, 1, 0, 0],
       [9, 8, 6, 6, 2],
       [4, 5, 4, 1, 0],
       [2, 5, 2, 3, 9]])

## Setting Coefficient Values

In [59]:
np_A = np_A.reshape(4, -1)
np_A

array([[0, 0, 1, 0, 0],
       [9, 8, 6, 6, 2],
       [4, 5, 4, 1, 0],
       [2, 5, 2, 3, 9]])

In [60]:
np_A[2, 2] = 0
np_A

array([[0, 0, 1, 0, 0],
       [9, 8, 6, 6, 2],
       [4, 5, 0, 1, 0],
       [2, 5, 2, 3, 9]])

In [61]:
np_A[1, :] = -3
np_A

array([[ 0,  0,  1,  0,  0],
       [-3, -3, -3, -3, -3],
       [ 4,  5,  0,  1,  0],
       [ 2,  5,  2,  3,  9]])

## Universal Functions

Many standard mathematical functions are reimplemented in numpy to ensure efficiency.

In [62]:
np.exp(np_A)

array([[  1.00000000e+00,   1.00000000e+00,   2.71828183e+00,
          1.00000000e+00,   1.00000000e+00],
       [  4.97870684e-02,   4.97870684e-02,   4.97870684e-02,
          4.97870684e-02,   4.97870684e-02],
       [  5.45981500e+01,   1.48413159e+02,   1.00000000e+00,
          2.71828183e+00,   1.00000000e+00],
       [  7.38905610e+00,   1.48413159e+02,   7.38905610e+00,
          2.00855369e+01,   8.10308393e+03]])

In [63]:
np.sqrt(np.exp(np_A))

array([[  1.        ,   1.        ,   1.64872127,   1.        ,   1.        ],
       [  0.22313016,   0.22313016,   0.22313016,   0.22313016,
          0.22313016],
       [  7.3890561 ,  12.18249396,   1.        ,   1.64872127,   1.        ],
       [  2.71828183,  12.18249396,   2.71828183,   4.48168907,  90.0171313 ]])

In [64]:
np_B = np.random.randint(100, size=20)
np_B = np_B.reshape(4, 5)

In [65]:
np_A + np_B

array([[ 1, 54, 64, 79, 45],
       [71, 72, 67, 82, 32],
       [28, 91, 28, 77, 59],
       [60, 40, 26, 34, 98]])

In [66]:
np_A * np_B

array([[   0,    0,   63,    0,    0],
       [-222, -225, -210, -255, -105],
       [  96,  430,    0,   76,    0],
       [ 116,  175,   48,   93,  801]])

In [67]:
np.maximum(np_A, np_B)

array([[ 1, 54, 63, 79, 45],
       [74, 75, 70, 85, 35],
       [24, 86, 28, 76, 59],
       [58, 35, 24, 31, 89]])

In [68]:
np.dot(np_A, np_B.T)

array([[   63,    70,    28,    24],
       [ -726, -1017,  -819,  -711],
       [  353,   756,   602,   438],
       [ 1040,  1233,  1293,  1233]])

## Exercise

Look into saving and loading numpy arrays.

In [69]:
np.save("np_A", np_A)

In [71]:
np.load("np_A.npy")

array([[ 0,  0,  1,  0,  0],
       [-3, -3, -3, -3, -3],
       [ 4,  5,  0,  1,  0],
       [ 2,  5,  2,  3,  9]])

## Exercise

Compare efficiency of `numpy` matrix multiplication to naive function using built-in structures.

In [104]:
# Defining a matrix as a list of lists in raw python
n = 200
M = [[np.random.randint(100) for _ in range(n)] for _ in range(n)]

In [105]:
%%time
M_square = [[0 for _ in range(n)] for _ in range(n)] 
for i in range(n):
    for j in range(n):
        for k in range(n):
            M_square[i][j] += M[i][k]*M[k][j]

CPU times: user 2.21 s, sys: 8 ms, total: 2.22 s
Wall time: 2.21 s


In [106]:
np_M = np.array(M)

In [107]:
%%time
np_M_square = np.dot(np_M, np_M)

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 9.78 ms


## Exercise

Simulate a random walk using both `numpy` and built-in structures. Compare both functions.

* Looking into the documentation of `matplotlib` write down a function enabling you to represent a random walk. 