NumPy is the standard numerical library available in the `python` environment. It allows quicker computations on array-like structures. Central objects in the `numpy` library are `ndarray`s. These are *homogenuous* $n$-dimensional arrays ; elements of the array are all of the same type. 

Efficiency of `ndarray` objects come from the fact that element-wise operations are `C` implemented to ensure low complexity. One can translate loop-like operations on array-like structures into available corresponding implementation for `ndarrays`. This process is called *vectorisation* ; it improves efficiency and must be on mind when dealing with scientific programming. 

## Defining an `ndarray` object

In [1]:
import numpy as np

In [5]:
np_matrix = np.array([[1, 2, 3, 4], [-1, 0, 1, 2]])
np_matrix

array([[ 1,  2,  3,  4],
       [-1,  0,  1,  2]])

One can build up a $2$-dimensional `ndarray` object as a list of lists. The matrix in such a case is given line by line. An `ndarray` object comes with a lot of attributes, we'll be seeing a number of them while going on. Here are the ones enclosing the shape of the array.

In [17]:
np_matrix.ndim

2

In [14]:
np_matrix.shape

(2, 4)

In many cases one to initialize an `ndarray`, either by giving random coefficients to the elements of the matrix or by giving a specified type matrix. Here are the standard available `ndarray`s.

In [21]:
np.zeros(4, dtype='float64')

array([ 0.,  0.,  0.,  0.])

In [23]:
np.zeros((3, 4), dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [27]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [28]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [19]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

To build up a random `ndarray` one can use available `numpy` built-in random generators.

In [39]:
np.random.rand(2, 4)

array([[ 0.4339348 ,  0.87146394,  0.54237017,  0.48556605],
       [ 0.10530611,  0.75602955,  0.96604758,  0.15673874]])

In [33]:
np.random.randn(2, 4)

array([[-0.67765235,  0.19945324,  0.72150524, -0.31913944],
       [ 0.21736231, -0.39406752,  0.53624122,  0.73058968]])

In [54]:
np.random.randint?

A useful way of building up matrices out of lists is to reshape the standard one-line corresponding numpy array object. 

In [56]:
np_A = np.random.randint(10, size=20)

In [63]:
np_A = np_A.reshape(2, -1)  # -1 here leaves the choice to python.

In [122]:
np_A.shape

(4, 5)

In [123]:
np_A.T

array([[ 1, -3,  1,  6],
       [ 7, -3,  1,  2],
       [ 2, -3,  0,  4],
       [ 6, -3,  2,  7],
       [ 0, -3,  3,  8]])

## Slicing 

There are many different ways of slicing an `ndarray`. One needs to be careful about the fact that some give back a view on a slice of the array others copy part of it.

In [53]:
np_matrix

array([[ 1,  2,  3,  4],
       [-1,  0,  1,  2]])

Standard slicing gives views on subelements of `ndarray`. 

In [40]:
np_matrix[1]

array([-1,  0,  1,  2])

In [42]:
np_matrix[1, 0]

-1

In [43]:
np_matrix[:, 0]

array([ 1, -1])

In [49]:
np_matrix[1:]

array([[-1,  0,  1,  2]])

In [52]:
np_matrix[1, 1:4]

array([0, 1, 2])

Boolean choices.

In [66]:
np_matrix[[False, True]]

array([[-1,  0,  1,  2]])

In [109]:
np_matrix[:, np_matrix[0] < 2]

array([[ 1],
       [-1]])

## Setting Coefficient Values

In [115]:
np_A = np_A.reshape(4, -1)
np_A

array([[1, 7, 2, 6, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 6, 2, 3],
       [6, 2, 4, 7, 8]])

In [117]:
np_A[2, 2] = 0
np_A

array([[1, 7, 2, 6, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 2, 3],
       [6, 2, 4, 7, 8]])

In [119]:
np_A[1, :] = -3
np_A

array([[ 1,  7,  2,  6,  0],
       [-3, -3, -3, -3, -3],
       [ 1,  1,  0,  2,  3],
       [ 6,  2,  4,  7,  8]])

## Universal Functions

Many standard mathematical functions are reimplemented in numpy to ensure efficiency.

In [124]:
np.exp(np_A)

array([[  2.71828183e+00,   1.09663316e+03,   7.38905610e+00,
          4.03428793e+02,   1.00000000e+00],
       [  4.97870684e-02,   4.97870684e-02,   4.97870684e-02,
          4.97870684e-02,   4.97870684e-02],
       [  2.71828183e+00,   2.71828183e+00,   1.00000000e+00,
          7.38905610e+00,   2.00855369e+01],
       [  4.03428793e+02,   7.38905610e+00,   5.45981500e+01,
          1.09663316e+03,   2.98095799e+03]])

In [126]:
np.sqrt(np.exp(np_A))

array([[  1.64872127,  33.11545196,   2.71828183,  20.08553692,   1.        ],
       [  0.22313016,   0.22313016,   0.22313016,   0.22313016,
          0.22313016],
       [  1.64872127,   1.64872127,   1.        ,   2.71828183,
          4.48168907],
       [ 20.08553692,   2.71828183,   7.3890561 ,  33.11545196,
         54.59815003]])

In [128]:
np_B = np.random.randint(100, size=20)
np_B = np_B.reshape(4, 5)

In [129]:
np_A + np_B

array([[16, 32, 14, 64, 10],
       [ 2,  2, 89,  7, 63],
       [24, 84,  9, 97, 56],
       [80, 23, 69, 29, 16]])

In [135]:
np_A * np_B

array([[  15,  175,   24,  348,    0],
       [ -15,  -15, -276,  -30, -198],
       [  23,   83,    0,  190,  159],
       [ 444,   42,  260,  154,   64]])

In [138]:
np.maximum(np_A, np_B)

array([[15, 25, 12, 58, 10],
       [ 5,  5, 92, 10, 66],
       [23, 83,  9, 95, 53],
       [74, 21, 65, 22,  8]])

In [141]:
np.dot(np_A, np_B.T)

array([[ 562,  284, 1192,  483],
       [-360, -534, -789, -570],
       [ 186,  228,  455,  163],
       [ 674, 1006, 1429,  964]])

## Exercise

Look into saving and loading numpy arrays.

## Exercise

Compare efficiency of `numpy` matrix multiplication to naive function using built-in structures.

## Exercise

Simulate a random walk using both `numpy` and built-in structures. Compare both functions.

* Looking into the documentation of `matplotlib` write down a function enabling you to represent a random walk. 